# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Documents\SoundLibrarys\New_New.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1346, 751)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../smith/Desktop/Downloads/Player_-_Audio_Full-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setAcceptDrops(False)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.topbarLibraryLocalCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryLocalCheckbox.setFont(font)
        self.topbarLibraryLocalCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryLocalCheckbox.setChecked(True)
        self.topbarLibraryLocalCheckbox.setObjectName("topbarLibraryLocalCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryLocalCheckbox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setWindowModality(QtCore.Qt.ApplicationModal)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.topbarLibraryFreeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryFreeCheckbox.setFont(font)
        self.topbarLibraryFreeCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryFreeCheckbox.setChecked(False)
        self.topbarLibraryFreeCheckbox.setObjectName("topbarLibraryFreeCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryFreeCheckbox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.topbarLibraryPaidCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryPaidCheckbox.setFont(font)
        self.topbarLibraryPaidCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryPaidCheckbox.setChecked(False)
        self.topbarLibraryPaidCheckbox.setTristate(False)
        self.topbarLibraryPaidCheckbox.setObjectName("topbarLibraryPaidCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryPaidCheckbox)
        self.topbarSettingsBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topbarSettingsBtn.sizePolicy().hasHeightForWidth())
        self.topbarSettingsBtn.setSizePolicy(sizePolicy)
        self.topbarSettingsBtn.setMouseTracking(False)
        self.topbarSettingsBtn.setCheckable(False)
        self.topbarSettingsBtn.setAutoDefault(False)
        self.topbarSettingsBtn.setDefault(False)
        self.topbarSettingsBtn.setFlat(False)
        self.topbarSettingsBtn.setObjectName("topbarSettingsBtn")
        self.horizontalLayout.addWidget(self.topbarSettingsBtn)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.mainWidget = QtWidgets.QHBoxLayout()
        self.mainWidget.setObjectName("mainWidget")
        self.searchResultsTable = QtWidgets.QTableView(self.centralwidget)
        self.searchResultsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.searchResultsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchResultsTable.setProperty("showDropIndicator", False)
        self.searchResultsTable.setDragEnabled(True)
        self.searchResultsTable.setDragDropOverwriteMode(False)
        self.searchResultsTable.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.searchResultsTable.setAlternatingRowColors(False)
        self.searchResultsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchResultsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.searchResultsTable.setSortingEnabled(True)
        self.searchResultsTable.setObjectName("searchResultsTable")
        self.mainWidget.addWidget(self.searchResultsTable)
        self.sidebar = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(300, 0))
        self.sidebar.setTabPosition(QtWidgets.QTabWidget.South)
        self.sidebar.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.sidebar.setElideMode(QtCore.Qt.ElideNone)
        self.sidebar.setMovable(True)
        self.sidebar.setObjectName("sidebar")
        self.metaTab = QtWidgets.QWidget()
        self.metaTab.setObjectName("metaTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.metaTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.metaAlbumImageLbl = QtWidgets.QLabel(self.metaTab)
        self.metaAlbumImageLbl.setMinimumSize(QtCore.QSize(100, 100))
        self.metaAlbumImageLbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.metaAlbumImageLbl.setBaseSize(QtCore.QSize(0, 0))
        self.metaAlbumImageLbl.setObjectName("metaAlbumImageLbl")
        self.verticalLayout_3.addWidget(self.metaAlbumImageLbl)
        self.metaList = QtWidgets.QListView(self.metaTab)
        self.metaList.setObjectName("metaList")
        self.verticalLayout_3.addWidget(self.metaList)
        self.sidebar.addTab(self.metaTab, "")
        self.playlistsTab = QtWidgets.QWidget()
        self.playlistsTab.setObjectName("playlistsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.playlistsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.playlistList = QtWidgets.QListView(self.playlistsTab)
        self.playlistList.setDragEnabled(False)
        self.playlistList.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.playlistList.setObjectName("playlistList")
        self.gridLayout_3.addWidget(self.playlistList, 0, 0, 1, 2)
        self.playlistAddBtn = QtWidgets.QPushButton(self.playlistsTab)
        self.playlistAddBtn.setObjectName("playlistAddBtn")
        self.gridLayout_3.addWidget(self.playlistAddBtn, 1, 0, 1, 1)
        self.playlistDeleteBtn = QtWidgets.QPushButton(self.playlistsTab)
        self.playlistDeleteBtn.setObjectName("playlistDeleteBtn")
        self.gridLayout_3.addWidget(self.playlistDeleteBtn, 1, 1, 1, 1)
        self.sidebar.addTab(self.playlistsTab, "")
        self.mainWidget.addWidget(self.sidebar)
        self.gridLayout.addLayout(self.mainWidget, 4, 0, 1, 1)
        self.player = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player.sizePolicy().hasHeightForWidth())
        self.player.setSizePolicy(sizePolicy)
        self.player.setMinimumSize(QtCore.QSize(0, 200))
        self.player.setSizeIncrement(QtCore.QSize(0, 0))
        self.player.setBaseSize(QtCore.QSize(0, 0))
        self.player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player.setObjectName("player")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.player)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.playerAlbumImageLbl = QtWidgets.QLabel(self.player)
        self.playerAlbumImageLbl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerAlbumImageLbl.sizePolicy().hasHeightForWidth())
        self.playerAlbumImageLbl.setSizePolicy(sizePolicy)
        self.playerAlbumImageLbl.setMinimumSize(QtCore.QSize(180, 180))
        self.playerAlbumImageLbl.setSizeIncrement(QtCore.QSize(64, 0))
        self.playerAlbumImageLbl.setText("")
        self.playerAlbumImageLbl.setObjectName("playerAlbumImageLbl")
        self.gridLayout_2.addWidget(self.playerAlbumImageLbl, 0, 1, 1, 1)
        self.waveform = QtWidgets.QGraphicsView(self.player)
        self.waveform.setObjectName("waveform")
        self.gridLayout_2.addWidget(self.waveform, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.player, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setShortcutVisibleInContextMenu(True)
        self.actionSearch.setObjectName("actionSearch")
        self.menuTools.addAction(self.actionSearch)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.sidebar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sound Library"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.topbarLibraryLocalCheckbox.setText(_translate("MainWindow", "Local"))
        self.topbarLibraryLocalCheckbox.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.topbarLibraryFreeCheckbox.setText(_translate("MainWindow", "Free"))
        self.topbarLibraryFreeCheckbox.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.topbarLibraryPaidCheckbox.setText(_translate("MainWindow", "Paid"))
        self.topbarLibraryPaidCheckbox.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.topbarSettingsBtn.setText(_translate("MainWindow", "Settings"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.metaAlbumImageLbl.setText(_translate("MainWindow", "Album Image"))
        self.sidebar.setTabText(self.sidebar.indexOf(self.metaTab), _translate("MainWindow", "Metadata"))
        self.playlistAddBtn.setText(_translate("MainWindow", "Add"))
        self.playlistDeleteBtn.setText(_translate("MainWindow", "Delete"))
        self.sidebar.setTabText(self.sidebar.indexOf(self.playlistsTab), _translate("MainWindow", "Playlists"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionSearch.setShortcut(_translate("MainWindow", "Return"))

