# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\Soundexy\Soundexy\GUI\DesignerFiles\Gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1346, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../smith/Desktop/Downloads/Player_-_Audio_Full-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.player = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player.sizePolicy().hasHeightForWidth())
        self.player.setSizePolicy(sizePolicy)
        self.player.setMinimumSize(QtCore.QSize(0, 200))
        self.player.setSizeIncrement(QtCore.QSize(0, 0))
        self.player.setBaseSize(QtCore.QSize(0, 0))
        self.player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player.setObjectName("player")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.player)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playerAlbumImageLbl = QtWidgets.QLabel(self.player)
        self.playerAlbumImageLbl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerAlbumImageLbl.sizePolicy().hasHeightForWidth())
        self.playerAlbumImageLbl.setSizePolicy(sizePolicy)
        self.playerAlbumImageLbl.setMinimumSize(QtCore.QSize(180, 180))
        self.playerAlbumImageLbl.setSizeIncrement(QtCore.QSize(64, 0))
        self.playerAlbumImageLbl.setText("")
        self.playerAlbumImageLbl.setScaledContents(True)
        self.playerAlbumImageLbl.setObjectName("playerAlbumImageLbl")
        self.verticalLayout.addWidget(self.playerAlbumImageLbl)
        self.currentTimeLabel = QtWidgets.QLabel(self.player)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.verticalLayout.addWidget(self.currentTimeLabel)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.player, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setAcceptDrops(False)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.topbarLibraryLocalCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryLocalCheckbox.setFont(font)
        self.topbarLibraryLocalCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryLocalCheckbox.setChecked(True)
        self.topbarLibraryLocalCheckbox.setObjectName("topbarLibraryLocalCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryLocalCheckbox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setWindowModality(QtCore.Qt.ApplicationModal)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.topbarLibraryFreeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryFreeCheckbox.setFont(font)
        self.topbarLibraryFreeCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryFreeCheckbox.setChecked(False)
        self.topbarLibraryFreeCheckbox.setObjectName("topbarLibraryFreeCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryFreeCheckbox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.topbarLibraryPaidCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.topbarLibraryPaidCheckbox.setFont(font)
        self.topbarLibraryPaidCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topbarLibraryPaidCheckbox.setChecked(False)
        self.topbarLibraryPaidCheckbox.setTristate(False)
        self.topbarLibraryPaidCheckbox.setObjectName("topbarLibraryPaidCheckbox")
        self.horizontalLayout.addWidget(self.topbarLibraryPaidCheckbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.mainWidget = QtWidgets.QHBoxLayout()
        self.mainWidget.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mainWidget.setObjectName("mainWidget")
        self.sidebar = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(300, 0))
        self.sidebar.setTabPosition(QtWidgets.QTabWidget.South)
        self.sidebar.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.sidebar.setElideMode(QtCore.Qt.ElideNone)
        self.sidebar.setMovable(True)
        self.sidebar.setObjectName("sidebar")
        self.metaTab = QtWidgets.QWidget()
        self.metaTab.setObjectName("metaTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.metaTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.metaAlbumImageLbl = QtWidgets.QLabel(self.metaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metaAlbumImageLbl.sizePolicy().hasHeightForWidth())
        self.metaAlbumImageLbl.setSizePolicy(sizePolicy)
        self.metaAlbumImageLbl.setMinimumSize(QtCore.QSize(100, 100))
        self.metaAlbumImageLbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.metaAlbumImageLbl.setSizeIncrement(QtCore.QSize(0, 0))
        self.metaAlbumImageLbl.setBaseSize(QtCore.QSize(0, 0))
        self.metaAlbumImageLbl.setText("")
        self.metaAlbumImageLbl.setScaledContents(True)
        self.metaAlbumImageLbl.setObjectName("metaAlbumImageLbl")
        self.verticalLayout_2.addWidget(self.metaAlbumImageLbl)
        self.metaArea = QtWidgets.QScrollArea(self.metaTab)
        self.metaArea.setWidgetResizable(True)
        self.metaArea.setObjectName("metaArea")
        self.metaAreaContents = QtWidgets.QWidget()
        self.metaAreaContents.setGeometry(QtCore.QRect(0, 0, 274, 261))
        self.metaAreaContents.setObjectName("metaAreaContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.metaAreaContents)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.metaArea.setWidget(self.metaAreaContents)
        self.verticalLayout_2.addWidget(self.metaArea)
        self.sidebar.addTab(self.metaTab, "")
        self.playlistsTab = QtWidgets.QWidget()
        self.playlistsTab.setObjectName("playlistsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.playlistsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.playlistDeleteBtn = QtWidgets.QPushButton(self.playlistsTab)
        self.playlistDeleteBtn.setObjectName("playlistDeleteBtn")
        self.gridLayout_3.addWidget(self.playlistDeleteBtn, 1, 1, 1, 1)
        self.playlistAddBtn = QtWidgets.QPushButton(self.playlistsTab)
        self.playlistAddBtn.setObjectName("playlistAddBtn")
        self.gridLayout_3.addWidget(self.playlistAddBtn, 1, 0, 1, 1)
        self.playlistWidgetContainer = QtWidgets.QGridLayout()
        self.playlistWidgetContainer.setObjectName("playlistWidgetContainer")
        self.gridLayout_3.addLayout(self.playlistWidgetContainer, 0, 0, 1, 2)
        self.sidebar.addTab(self.playlistsTab, "")
        self.mainWidget.addWidget(self.sidebar)
        self.gridLayout.addLayout(self.mainWidget, 4, 0, 1, 1)
        self.lowerPlayer = QtWidgets.QGridLayout()
        self.lowerPlayer.setHorizontalSpacing(10)
        self.lowerPlayer.setObjectName("lowerPlayer")
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.lowerPlayer.addItem(spacerItem1, 0, 5, 1, 1)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setMaximumSize(QtCore.QSize(185, 16777215))
        self.volumeSlider.setAutoFillBackground(False)
        self.volumeSlider.setStyleSheet("")
        self.volumeSlider.setMaximum(125)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.lowerPlayer.addWidget(self.volumeSlider, 0, 0, 1, 1)
        self.loopCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.loopCheckBox.setTristate(False)
        self.loopCheckBox.setObjectName("loopCheckBox")
        self.lowerPlayer.addWidget(self.loopCheckBox, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lowerPlayer.addWidget(self.line_3, 0, 1, 1, 1)
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setText("")
        self.messageLabel.setObjectName("messageLabel")
        self.lowerPlayer.addWidget(self.messageLabel, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowerPlayer.addItem(spacerItem2, 0, 6, 1, 1)
        self.selectedChannelsLayout = QtWidgets.QHBoxLayout()
        self.selectedChannelsLayout.setSpacing(0)
        self.selectedChannelsLayout.setObjectName("selectedChannelsLayout")
        self.lowerPlayer.addLayout(self.selectedChannelsLayout, 0, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lowerPlayer.addWidget(self.line_4, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.lowerPlayer, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuPlayer = QtWidgets.QMenu(self.menubar)
        self.menuPlayer.setObjectName("menuPlayer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setShortcutVisibleInContextMenu(True)
        self.actionSearch.setObjectName("actionSearch")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionImport_Directory = QtWidgets.QAction(MainWindow)
        self.actionImport_Directory.setObjectName("actionImport_Directory")
        self.actionImport_Audio_File = QtWidgets.QAction(MainWindow)
        self.actionImport_Audio_File.setObjectName("actionImport_Audio_File")
        self.menuFile.addAction(self.actionImport_Directory)
        self.menuFile.addAction(self.actionImport_Audio_File)
        self.menuTools.addAction(self.actionSearch)
        self.menuPlayer.addAction(self.actionPlay)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuPlayer.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.sidebar.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sound Library"))
        self.currentTimeLabel.setText(_translate("MainWindow", "Current Time: 00:00:000"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.topbarLibraryLocalCheckbox.setText(_translate("MainWindow", "Local"))
        self.topbarLibraryLocalCheckbox.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.topbarLibraryFreeCheckbox.setText(_translate("MainWindow", "Free"))
        self.topbarLibraryFreeCheckbox.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.topbarLibraryPaidCheckbox.setText(_translate("MainWindow", "Paid"))
        self.topbarLibraryPaidCheckbox.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.sidebar.setTabText(self.sidebar.indexOf(self.metaTab), _translate("MainWindow", "Metadata"))
        self.playlistDeleteBtn.setText(_translate("MainWindow", "Delete"))
        self.playlistAddBtn.setText(_translate("MainWindow", "Add"))
        self.sidebar.setTabText(self.sidebar.indexOf(self.playlistsTab), _translate("MainWindow", "Playlists"))
        self.loopCheckBox.setText(_translate("MainWindow", "Loop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuPlayer.setTitle(_translate("MainWindow", "Player"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionSearch.setShortcut(_translate("MainWindow", "Return"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Space"))
        self.actionImport_Directory.setText(_translate("MainWindow", "Import Directory"))
        self.actionImport_Audio_File.setText(_translate("MainWindow", "Import Audio File"))

